// 工程化/Monorepo/pnpm-monorepo-demo/packages/react-ui/src/components/Button.jsx
import './Button.css';
export default function Button ({ type, children }) {
    let _type = 'primary';

    if ([
        'primary',
        'success',
        'warn',
        'danger'
    ].includes(type)) {
        _type = type;
    }

    return <button className={ _type }>{ children }</button>
}

// 工程化/Monorepo/pnpm-monorepo-demo/packages/vue-ui/src/components/Button.vue
<template>
<button :class="type"><slot></slot></button>
</template>

<script setup>
const props = defineProps({
    type: {
        default: 'primary',
        validator: (value) => [
            'primary',
            'success',
            'warn',
            'danger'
        ].includes(value)
    }
})
</script>

<style scoped>
.primary {
    background-color: blue;
    color: #fff;
}

.success {
    background-color: green;
    color: #fff;
}

.warn {
    background-color: orange;
    color: #000;
}

.danger {
    background-color: red;
    color: #fff;
}
</style>
